### PR TITLE
Make 0 results more fun (#450)

### PR DESCRIPTION
**Pull request by ezittel**
It's probably not more fun, but the link is added.

### CODE REVIEW

**Comment by toddmedema** [comment]
Awesome! Can you attach a screenshot of the new UI?

**Comment by ezittel** [comment]
Looks something like:
image

**Comment by toddmedema** [comment]
Looks good to me! Note that for more complicated UI features, we like to use screenshots for both desktop and mobile (via the Chrome mobile emulator in dev tools) since most of our players use the mobile experience. But this is a straightforward addition, so we can skip that this time :)

**Comment by ezittel** [comment]
Okay, good to know.  Although I'm not sure I like the mobile results:

**Comment by ezittel** [comment]
I cleaned this up, shortened the text a little so it looks good on 
mobile as well, then attached both screenshots to a new PR.

Sorry for the confusion.

**Pull request merged**
